language: python

python:
  - "2.7"

# To generate the encrypted credentials, follow instructions at
# https://docs.travis-ci.com/user/deployment/google-app-engine/.
before_install:
  - openssl aes-256-cbc -K $encrypted_06a621a919cf_key -iv $encrypted_06a621a919cf_iv
    -in gae-service-account.json.enc -out gae-service-account.json -d

install:
  - pip install sphinx

script:
  - mvn package # compile / package the war
  - mvn jspc:jspc # compile jsp files
  # TODO: eventually add RST ?

deploy:
  - provider: script
    script: 'mvn appengine:update -Dappengine.additionalParams="--service_account_json_key_file=gae-service-account.json"'
    skip_cleanup: true
    on:
      branch: master
